### ISSUE TITLE
og meta on Facebook post is broken

### ISSUE THREAD

**Issue by mousems** [sitcon-tw/camp2015#1]
http://sitcon.camp/2015/ for [Facebook debug tool](https://developers.facebook.com/tools/debug/og/object/)

return:
Critical Errors 
Could Not Follow Redirect:URL requested a HTTP redirect, but it could not be followed.

**Comment by sunset1995** [comment]
thanks~!
already fix

It seem that Facebook crawl page line by line,
so I just simply remove preprocessor's htmlmin.
it works now.
